services:
- type: web
  name: cryptr_developer_onboarding_hasura_develop
  env: docker
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: cryptr_developer_onboarding
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
# Uncomment to automatically generate an admin secret
# for your Hasura instance. The value is visible under
# Environment on the Render dashboard.
 - key: HASURA_GRAPHQL_ADMIN_SECRET
   generateValue: true
databases:
- name: cryptr_developer_onboarding_develop
